"""
Comparing ordinal classifiers
=============================

Every skordinal classifier on the same synthetic problem, ranked by two
ordinal metrics.
"""

# %%
# A synthetic ordinal dataset
# ---------------------------
# 600 samples, 8 features and 5 ordered classes, generated by thresholding
# a noisy linear latent score. A stratified 70/30 split keeps every class
# represented in both partitions.

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from skordinal.datasets import make_ordinal_classification

X, y = make_ordinal_classification(
    n_samples=600, n_features=8, n_classes=5, random_state=0
)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=0, stratify=y
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print(f"Train: {X_train.shape},  Test: {X_test.shape}")

# %%
# The thirteen classifiers
# ------------------------
# Threshold models (``POM``, ``LogisticAT``, ``LogisticIT``), neural
# networks (``NNPOM``, ``NNOP``, ``ELMOP``), a kernel discriminant
# (``KDLOR``), support vector machines (``SVOR``, ``REDSVM``), boosting
# (``ORBoost``) and the three meta-estimators that build an ordinal
# classifier out of a scikit-learn one (``OrdinalDecomposition``,
# ``RegressorWrapper``, ``CostSensitiveWrapper``). All run with their
# defaults and a fixed seed, except that ``NNPOM`` gets enough
# iterations to converge.

from skordinal.classifiers import (
    ELMOP,
    KDLOR,
    NNOP,
    NNPOM,
    POM,
    REDSVM,
    SVOR,
    CostSensitiveWrapper,
    LogisticAT,
    LogisticIT,
    ORBoost,
    OrdinalDecomposition,
    RegressorWrapper,
)

classifiers = {
    "POM": POM(),
    "LogisticAT": LogisticAT(),
    "LogisticIT": LogisticIT(),
    "NNPOM": NNPOM(max_iter=5000, random_state=0),
    "NNOP": NNOP(random_state=0),
    "ELMOP": ELMOP(random_state=0),
    "KDLOR": KDLOR(),
    "SVOR": SVOR(),
    "REDSVM": REDSVM(),
    "ORBoost": ORBoost(),
    "OrdinalDecomposition": OrdinalDecomposition(),
    "RegressorWrapper": RegressorWrapper(),
    "CostSensitiveWrapper": CostSensitiveWrapper(),
}

# %%
# Fit and score
# -------------
# Each classifier is fitted on the scaled training set and scored on the
# held-out test set with linear weighted kappa (higher is better) and MAE
# (lower is better).

from skordinal.metrics import mean_absolute_error, weighted_kappa

results = {}
for name, clf in classifiers.items():
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    kap = weighted_kappa(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    results[name] = {"kappa": kap, "mae": mae}
    print(f"{name:22s}  kappa={kap:.3f}  MAE={mae:.3f}")

# %%
# Ranking
# -------
# Sorted by kappa, highest first. Three pairs share their scores.
# ``LogisticAT`` and ``LogisticIT`` predict the same label on every test
# sample, their losses differing only in which thresholds each sample is
# charged against, and so do ``SVOR`` and ``REDSVM``. ``POM`` and
# ``OrdinalDecomposition``, both linear logistic models, disagree on four
# samples and tie by coincidence.

import matplotlib.pyplot as plt

names_sorted = sorted(results, key=lambda n: results[n]["kappa"], reverse=True)
kappas = [results[n]["kappa"] for n in names_sorted]
maes = [results[n]["mae"] for n in names_sorted]

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 6))

ax1.barh(names_sorted, kappas, color="steelblue")
ax1.set_xlabel("Linear weighted kappa (higher is better)")
ax1.set_title("Kappa ranking")
ax1.set_xlim(0, 1)
ax1.invert_yaxis()

ax2.barh(names_sorted, maes, color="darkorange")
ax2.set_xlabel("MAE (lower is better)")
ax2.set_title("MAE ranking")
ax2.invert_yaxis()

fig.tight_layout()
plt.show()
