version: 2
updates:
  # Maintain dependencies for GitHub Actions as recommended in SPEC8:
  # https://github.com/scientific-python/specs/pull/325
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"
    labels:
      - "Build / CI"
      - "dependencies"
    commit-message:
      prefix: "MNT"

  # Maintain the Python runtime dependencies declared in pyproject.toml
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      python-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
    commit-message:
      prefix: "MNT"
